name: CI
on:
  
  push:
  #branches: [ "feature-*!" ]
  #pull_request:
  #branches: [ "main" ]
  
  workflow_dispatch:
 
jobs:
  
  build:
   
    runs-on: ubuntu-latest
  
    steps:

      - uses: actions/checkout@v3

      - name: Run a multi-line script
        run: |
          echo "Modificación del mensaje del microservicio"
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: test
        run: |
          echo "paso dos agregado"
